name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
        with:
          ref: $github.event.client_payload.branch

      - name: On my_custom_webhook step 1...
        if: github.event.client_payload.url == 'testing'
        env:
          DEPLOY_PRIME_URL: ${{ github.event.client_payload.url }}
        run: |
          echo "Hello From my_custom_webhook.." 
          echo $DEPLOY_PRIME_URL
          echo $github.event.client_payload.url

      - name: On my_custom_webhook step2...
        env:
          DEPLOY_PRIME_URL: ${{ github.event.client_payload.test }}
        if: github.event.client_payload.url == 'testing'
        run: |
          echo "Hello From my_custom_webhook NR 2..." 
          echo $DEPLOY_PRIME_URL
          echo ${{ github.ref }}

      - name: On my_custom_webhook do XYZ...
        if: github.event.action == 'my_custom_webhook_2'
        run: |
          echo "Hello From my_custom_webhook_2...doing XYZ"
