name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: On my_custom_webhook do ABC...
        run: |
          echo "Hello From my_custom_webhook...doing ABC"
