name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: On my_custom_webhook do ABC...
        env:
          DEPLOY_PRIME_URL: ${{ github.event.client_payload.url }}
        if: github.event.client_payload.url == 'testing'
        run: |
          echo "Hello From my_custom_webhook...doing ABC" 
        -name: Testing after if
        run: |
          echo "Hello From testing"

      - name: On my_custom_webhook do XYZ...
        if: github.event.action == 'my_custom_webhook_2'
        run: |
          echo "Hello From my_custom_webhook_2...doing XYZ"
